import React from 'react'
import './UniversalMainPageComponent.css'
import DynamicTablet from '../components/DynamicTablet'

const dict_array = [
  [
    {
      'column_name':'Room_id',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Room_no',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Hotel_id',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Status',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Price',
      'column_data':'ASDHAKDSFAADFA'
    }

  ],
  [
    {
      'column_name':'Room_id',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Room_no',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Hotel_id',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Status',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Price',
      'column_data':'ASDHAKDSFAADFA'
    }

  ],
  [
    {
      'column_name':'Room_id',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Room_no',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Hotel_id',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Status',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Price',
      'column_data':'ASDHAKDSFAADFA'
    }

  ],
  [
    {
      'column_name':'Room_id',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Room_no',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Hotel_id',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Status',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Price',
      'column_data':'ASDHAKDSFAADFA'
    }

  ],
  [
    {
      'column_name':'Room_id',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Room_no',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Hotel_id',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Status',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Price',
      'column_data':'ASDHAKDSFAADFA'
    }

  ],
  [
    {
      'column_name':'Room_id',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Room_no',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Hotel_id',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Status',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Price',
      'column_data':'ASDHAKDSFAADFA'
    }

  ],
  [
    {
      'column_name':'Room_id',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Room_no',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Hotel_id',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Status',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Price',
      'column_data':'ASDHAKDSFAADFA'
    }

  ],
  [
    {
      'column_name':'Room_id',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Room_no',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Hotel_id',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Status',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Price',
      'column_data':'ASDHAKDSFAADFA'
    }

  ],
  [
    {
      'column_name':'Room_id',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Room_no',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Hotel_id',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Status',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Price',
      'column_data':'ASDHAKDSFAADFA'
    }

  ],
  [
    {
      'column_name':'Room_id',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Room_no',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Hotel_id',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Status',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Price',
      'column_data':'ASDHAKDSFAADFA'
    }

  ],
  [
    {
      'column_name':'Room_id',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Room_no',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Hotel_id',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Status',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Price',
      'column_data':'ASDHAKDSFAADFA'
    }

  ],
  [
    {
      'column_name':'Room_id',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Room_no',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Hotel_id',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Status',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Price',
      'column_data':'ASDHAKDSFAADFA'
    }

  ],
  [
    {
      'column_name':'Room_id',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Room_no',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Hotel_id',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Status',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Price',
      'column_data':'ASDHAKDSFAADFA'
    }

  ],
  [
    {
      'column_name':'Room_id',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Room_no',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Hotel_id',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Status',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Price',
      'column_data':'ASDHAKDSFAADFA'
    }

  ],
  [
    {
      'column_name':'Room_id',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Room_no',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Hotel_id',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Status',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Price',
      'column_data':'ASDHAKDSFAADFA'
    }

  ],
  [
    {
      'column_name':'Room_id',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Room_no',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Hotel_id',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Status',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Price',
      'column_data':'ASDHAKDSFAADFA'
    }

  ],
  [
    {
      'column_name':'Room_id',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Room_no',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Hotel_id',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Status',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Price',
      'column_data':'ASDHAKDSFAADFA'
    }

  ],
  [
    {
      'column_name':'Room_id',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Room_no',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Hotel_id',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Status',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Price',
      'column_data':'ASDHAKDSFAADFA'
    }

  ],
  [
    {
      'column_name':'Room_id',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Room_no',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Hotel_id',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Status',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Price',
      'column_data':'ASDHAKDSFAADFA'
    }

  ],
  [
    {
      'column_name':'Room_id',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Room_no',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Hotel_id',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Status',
      'column_data':'ASDHAKDSFAADFA'
    },
    {
      'column_name':'Price',
      'column_data':'ASDHAKDSFAADFA'
    }

  ],

]

function Billing() {
  return (
    <div className='universal_page_component_div'>
      {dict_array.map((dict_individual_card) => {
        return(
          <DynamicTablet
            incoming_data = {dict_individual_card}
            origin_card_title = 'Billing Object'
          />
        )
      })}
    </div>
  )
}

export default Billing